name: su_thesis_book
description: Thesis Book of Sonargaon University
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  file_picker: ^5.3.3
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_cached_pdfview: ^0.4.2
  flutter_localizations:
    sdk: flutter
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  hydrated_bloc: ^9.1.2
  image_cropper: ^5.0.0
  image_picker: ^1.0.2
  intl: ^0.18.0
  path_provider: ^2.0.15
  

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
