name: su_thesis_book
description: Thesis Book of Sonargaon University
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_cached_pdfview: ^0.4.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^5.1.0
  hydrated_bloc: ^9.1.2
  intl: ^0.18.0
  path_provider: ^2.0.15

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
